project:
  type: website
  output-dir: docs

website:
  title: "Banking : Pipes & Pits"
  draft-mode: unlinked
  navbar:
    left:
      - text: "Pipes"
        href: pipes.qmd
      - text: "Pits"
        href: pits.qmd
      - text: "Lab"
        menu:
          - text: "Overview"
            href: lab.qmd
          - text: "Projects"
            href: projects.qmd
          - text: "Data blog"
            href: data-blog.qmd
          - text: "Math & Stats"
            href: math&stat.qmd
          - text: "Wire"
            href: wire.qmd
    right:
      - text: Subscribe
        href: https://ashwinbijur.substack.com
      - icon: github
        href: https://github.com/ashwinbijur/
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle: true
    default-mode: light
    css: styles.css



